Bistooltip_classes = {}
Bistooltip_phases = {}

Bistooltip_classes_indexes = {
    ["Druid"] = 1,
    ["Hunter"] = 2,
    ["Mage"] = 3,
    ["Paladin"] = 4,
    ["Priest"] = 5,
    ["Rogue"] = 6,
    ["Shaman"] = 7,
    ["Warlock"] = 8,
    ["Warrior"]= 9
}

Bistooltip_spec_icons = {};
Bistooltip_spec_icons["Druid"] = {};
Bistooltip_spec_icons["Druid"]["classIcon"] = 625999;
Bistooltip_spec_icons["Druid"]["Balance Dps"] = 136096;
Bistooltip_spec_icons["Druid"]["Tank"] = 132276;
Bistooltip_spec_icons["Druid"]["Feral Dps"] = 132115;
Bistooltip_spec_icons["Druid"]["Healer"] = 136041;
Bistooltip_spec_icons["Hunter"] = {};
Bistooltip_spec_icons["Hunter"]["classIcon"] = 626000;
Bistooltip_spec_icons["Hunter"]["Dps"] = 626000;
Bistooltip_spec_icons["Mage"] = {};
Bistooltip_spec_icons["Mage"]["classIcon"] = 626001;
Bistooltip_spec_icons["Mage"]["Dps"] = 626001;
Bistooltip_spec_icons["Mage"]["Healer"] = 132871;
Bistooltip_spec_icons["Paladin"] = {};
Bistooltip_spec_icons["Paladin"]["classIcon"] = 626003;
Bistooltip_spec_icons["Paladin"]["Healer"] = 135920;
Bistooltip_spec_icons["Paladin"]["Tank"] = 135893;
Bistooltip_spec_icons["Paladin"]["Dps"] = 135873;
Bistooltip_spec_icons["Priest"] = {};
Bistooltip_spec_icons["Priest"]["classIcon"] = 626004;
Bistooltip_spec_icons["Priest"]["Healer"] = 135987;
Bistooltip_spec_icons["Priest"]["Dps"] = 136207;
Bistooltip_spec_icons["Rogue"] = {};
Bistooltip_spec_icons["Rogue"]["classIcon"] = 626005;
Bistooltip_spec_icons["Rogue"]["Dps"] = 626005;
Bistooltip_spec_icons["Rogue"]["Tank"] = 236550;
Bistooltip_spec_icons["Shaman"] = {};
Bistooltip_spec_icons["Shaman"]["classIcon"] = 626006;
Bistooltip_spec_icons["Shaman"]["Elemental Dps"] = 136048;
Bistooltip_spec_icons["Shaman"]["Enhancement Dps"] = 136051;
Bistooltip_spec_icons["Shaman"]["Tank"] = 134963;
Bistooltip_spec_icons["Shaman"]["Healer"] = 136052;
Bistooltip_spec_icons["Warlock"] = {};
Bistooltip_spec_icons["Warlock"]["classIcon"] = 626007;
Bistooltip_spec_icons["Warlock"]["Dps"] = 626007;
Bistooltip_spec_icons["Warlock"]["Tank"] = 237558;
Bistooltip_spec_icons["Warrior"] = {};
Bistooltip_spec_icons["Warrior"]["classIcon"] = 626008;
Bistooltip_spec_icons["Warrior"]["Dps"] = 132347;
Bistooltip_spec_icons["Warrior"]["Tank"] = 134952;
